services:
  mongodb:
    image: mongo:7.0
    container_name: proppulse_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: proppulse_crm

  redis:
    image: redis:7.2-alpine
    container_name: proppulse_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
